
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer

import sys
from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage
import main as m

#Start GUI window.
window = Tk()
window.geometry("851x486")
window.configure(bg = "#343333")

"""def button_click(GUI_command):
    server.get()
    username.get()
    password.get()"""

canvas = Canvas(
    window,
    bg = "#343333",
    height = 486,
    width = 851,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)
canvas.place(x = 0, y = 0)

#Local path widgets.
canvas.create_text(
    20.0,
    120.0,
    anchor="nw",
    text="Local Files",
    fill="#FFFFFF",
    font=("Arial BoldMT", 13 * -1)
)
local_path = Entry(
    bd=0,
    bg="white",
    fg="black",
    highlightthickness=0,
    readonlybackground='white',
    state='readonly'
)
local_path.place(
    x=119.0,
    y=115.0,
    width=296.0,
    height=18.0
)

#Remote path widgets.
canvas.create_text(
    435.0,
    120.0,
    anchor="nw",
    text="Remote Files",
    fill="#FFFFFF",
    font=("Arial BoldMT", 13 * -1)
)
remote_path = Entry(
    bd=0,
    bg="white",
    fg="black",
    highlightthickness=0,
    readonlybackground='white',
    state='readonly'
)
remote_path.place(
    x=534.0,
    y=115.0,
    width=296.0,
    height=18.0
)

#Server widgets.
canvas.create_text(
    20.0,
    19.0,
    anchor="nw",
    text="Server",
    fill="#FFFFFF",
    font=("Arial BoldMT", 13 * -1)
)
server = Entry(
    bd=0,
    bg="white",
    fg="black",
    highlightthickness=0,
    insertbackground="black"
)
server.place(
    x=67.0,
    y=11.0,
    width=150.0,
    height=18.0
)

#Username widgets.
canvas.create_text(
    232.0,
    19.0,
    anchor="nw",
    text="Username",
    fill="#FFFFFF",
    font=("Arial BoldMT", 13 * -1)
)
username = Entry(
    bd=0,
    bg="white",
    fg="black",
    highlightthickness=0,
    insertbackground="black"
)
username.place(
    x=302.0,
    y=11.0,
    width=150.0,
    height=18.0
)

#Password widgets.
canvas.create_text(
    465.0,
    19.0,
    anchor="nw",
    text="Password",
    fill="#FFFFFF",
    font=("Arial BoldMT", 13 * -1)
)
password = Entry(
    bd=0,
    bg="white",
    fg="black",
    highlightthickness=0,
    insertbackground="black",
    show="*"
)
password.place(
    x=535.0,
    y=11.0,
    width=150.0,
    height=18.0
)

#Login GUI button.
login_button = Button(
    text="Login",
    borderwidth=0,
    highlightthickness=0,
    command=lambda: m.main("login"),
    relief="flat"
)
login_button.place(
    x=693.0,
    y=11.0,
    width=137.0,
    height=20.0
)

#Logout GUI button.
logout_button = Button(
    text="Logout",
    borderwidth=0,
    highlightthickness=0,
    command=lambda: m.main("logoff"),
    relief="flat"
)
logout_button.place(
    x=693.0,
    y=40.0,
    width=137.0,
    height=20.0
)


canvas.create_rectangle(
    20.0,
    140.0,
    415.0,
    471.0,
    fill="#D9D9D9",
    outline="")

canvas.create_rectangle(
    435.0,
    140.0,
    830.0,
    471.0,
    fill="#000000",
    outline="")


window.resizable(False, False)
window.mainloop()
